### ISSUE TITLE
Can I save Liger object on disk?

### ISSUE THREAD

**Issue by rLannes** [welch-lab/pyliger#1]
Hi, thank you for developing Liger,

I would like to know If and How I can save and retrieve Liger object on disk.
Unfortunately, I did not see this information on the vignette.

Romain

**Comment by Lulu0015** [comment]
Hi Romain,

Thank you for choosing PyLiger!
We are currently working on functions to store Liger object on disk. Alternatively, you could save each individual AnnData object from adata_list for now.

Best,
Lu Lu
