### ISSUE TITLE
`plot_qc` does not exist?

### ISSUE THREAD

**Issue by hojaeklee** [welch-lab/pyliger#4]
I git cloned the repo so I could debug more easily on my end, but it comes with its own import errors:

In file: `pyliger/plotting/__init__.py`, line 1:

Line `from ._qc import plot_qc` throws an error. I guess the _qc.py got moved to the `preprocessing` folder instead of `plotting`? 

For current workaround I will comment the line since `plot_qc` doesn't seem to exist/renamed.

**Comment by LemonadeCow** [comment]
I'm gonna check it out.
