### ISSUE TITLE
plot_gene_loadings

### ISSUE THREAD

**Issue by bromleyjd** [welch-lab/pyliger#5]
Thanks for making an accessible platform in python! There appears to be a couple bugs with some of the functions associated with pyliger - I've a screenshot of one issue below. Additionally, when "pip" installing the package many of the plotting functions are not incorporated, which requires the user to clone your repository. 

<img width="659" alt="Screen Shot 2022-05-02 at 9 32 36 PM" src="https://user-images.githubusercontent.com/60758390/166392345-cd53bd13-1203-4679-b922-1be6fb8c7b97.png">
<img width="650" alt="Screen Shot 2022-05-02 at 9 32 55 PM" src="https://user-images.githubusercontent.com/60758390/166392369-8efe1dd2-3c52-4b2a-b4f3-d19e1941b5fa.png">

**Comment by theAeon** [comment]
dupe #16
