### ISSUE TITLE
How to save the Liger object?

### ISSUE THREAD

**Issue by lijinbio** [welch-lab/pyliger#7]
Hi, after calculating the liger analysis, I want to save the Liger object. Could you please help suggest how could I do that? Thanks.

**Comment by Lulu0015** [comment]
Hi,

Thanks for your interest in PyLiger! Currently, we don’t have any existing functions to save and restore the object. We plan to include functions to save and restore the object in our next update. But for now you may save each Anndata object in the adata_list using this customized code. 

for adata in liger_object.adata_list:
    adata.write_h5ad(filename=‘YOUR DIRECTORY’ + adata.uns['sample_name'] + '.h5ad')

And restoring the object can be done with this code:

folder_path =‘YOUR DIRECTORY’
file_list = os.listdir(folder_path)

result_list = []
for file in os.listdir(folder_path):
    if file.endswith(".h5ad"):
        file_name = os.path.join(folder_path, file)
        result_list.append(read_h5ad(file_name))
        
liger_object = pyliger.create_liger(result_list)
umap_coords = np.concatenate([adata.obsm['umap_coords'] for adata in liger_object.adata_list])
liger_object.tsne_coords = pd.DataFrame(umap_coords, columns=['tsne1', 'tsne2'])

Thanks,
Lu Lu
