### ISSUE TITLE
NameError: name 'njit' is not defined

### ISSUE THREAD

**Issue by yuxiaokang-source** [welch-lab/pyliger#8]
when I use `pip install pyliger`, I get this error. How to solve it? thank you

![image](https://user-images.githubusercontent.com/59059267/221220781-8c163e79-8e69-4fa5-8aed-9f19eab45386.png)

**Comment by theAeon** [comment]
Typo on my part-just comment that line out for now. I'll cut a release later today.

**Comment by theAeon** [comment]
Should be fixed with v0.1.2.

**Comment by kokp2000** [comment]
Hi theAeon and yuxiaokang-source,

Can I know if this issue has solved?

I am experiencing the same problem when importing pyliger.
![image](https://user-images.githubusercontent.com/56579450/223192284-59b99c9e-e402-4adc-92f4-b86a54dfed9b.png)

Here is the package list of my environment, and the version of pyliger is 0.1.2.
![Picture1](https://user-images.githubusercontent.com/56579450/223192344-4073b801-110c-4cbf-9174-c31ff267c43c.jpg)

**Comment by theAeon** [comment]
My bad-seems I typoed in two separate files. Cutting a release right now.

**Comment by theAeon** [comment]
Just pushed it as v0.1.3. Let me know if it works.

**Comment by kokp2000** [comment]
Thank you for the quick response!

Now it works with v0.1.3.
